# Generated by Django 4.2.5 on 2023-09-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='name_products',
            new_name='name_product',
        ),
    ]
